---

- name: Slurp the deploy key
  slurp:
    src: '{{ git_checkout__app_home_path }}/.ssh/id_rsa.pub'
  register: git_checkout__register_deploy_key

- name: Create a json formatted deploy key
  set_fact:
    git_checkout__register_deploy_key_data:
      title: '{{ git_checkout__name }}@{{ ansible_fqdn }} deployed by Ansible'
      key: '{{ git_checkout__register_deploy_key.content | b64decode | trim }}'

- name: Transfer the deploy key to GitLab
  uri:
    url: 'https://{{ git_checkout__git_service_host }}/api/v4/projects/{{ git_checkout__git_service_account }}%2F{{ git_checkout__git_service_repo }}/deploy_keys'
    method: 'POST'
    body_format: 'json'
    body: '{{ git_checkout__register_deploy_key_data }}'
    headers:
            Private-Token: '{{ git_checkout__deploy_key_token }}'
    status_code: '200,201'
  when: git_checkout__git_service_type == 'gitlab'

- name: Transfer the deploy key to GitHub
  uri:
    url: 'https://api.github.com/repos/{{ git_checkout__git_service_account }}/{{ git_checkout__git_service_repo }}/keys'
    method: 'POST'
    body_format: 'json'
    body: '{{ git_checkout__register_deploy_key_data }}'
    url_username: '{{ git_checkout__deploy_key_user }}'
    url_password: '{{ git_checkout__deploy_key_token }}'
    status_code: '200,201'
  when: git_checkout__git_service_type == 'github'

- name: Add server key do known hosts
  known_hosts:
    name: '{{ git_checkout__git_service_host }}'
    key: '{{ git_checkout__git_service_sshkey }}'  
  become_user: '{{ git_checkout__user }}'
  when: git_checkout__git_service_sshkey != False
